version: '3'

services:
  web:
   build: ./web
   environment:
      - APACHE_RUN_USER=#1000
   volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
   ports:
      - 8080:80
   working_dir: ${APP_PATH_CONTAINER}

  db:
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
      MYSQL_ROOT_PASSWORD: root
   volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 6080:80
      environment:
        - PMA_ARBITRARY=1

  composer:
    image: composer:2
    volumes:
     - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install
